.\" $Id: fiasco_get_error_message.3,v 1.1 2000/06/14 19:07:02 hafner Exp $
.TH fiasco 3 "April, 2000" "FIASCO" "Fractal Image And Sequence COdec"

.SH NAME
.B  fiasco_get_error_message
\- return string describing last error catched in FIASCO library

.SH SYNOPSIS
.B #include <fiasco.h>
.sp
.BI "const char * "
.fi
.BI "fiasco_get_error_message (void);"
.fi

.SH DESCRIPTION
The \fBfiasco_get_error_message()\fP function returns a string
describing the last error that has been catched in the FIASCO library.

.SH RETURN VALUE
The function \fBfiasco_get_error_message()\fP returns the appropriate
description string, or an empty string if no error has been catched so
far.

.SH "SEE ALSO"
.br
.BR fiasco_options "(3), " fiasco_coder (3), 
.br
.BR fiasco_decoder "(3), " fiasco_renderer (3)
.br

Ullrich Hafner, Juergen Albert, Stefan Frank, and Michael Unger.
\fBWeighted Finite Automata for Video Compression\fP, IEEE Journal on
Selected Areas In Communications, January 1998
.br
Ullrich Hafner. \fBLow Bit-Rate Image and Video Coding with Weighted
Finite Automata\fP, Ph.D. thesis, Mensch & Buch Verlag, ISBN
3-89820-002-7, October 1999.

.SH AUTHOR
Ullrich Hafner <hafner@bigfoot.de>
